# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f53a9cb5393937de56c31e310beba4c76f2fb9f8ad4731aa403409ddf5ef1905caa261ffee829ba6c4aa0a2cab1fd29c3b09b6def8b7dc57dd3539ef146437cb

test:
  secret_key_base: 8aad2d0c4772f2bc552d4b2525d5b9bb8853666e4e2e932493714a5eb8d15b2159075e31636e2dbd95722ab55956f68102f5a5c46c3b6ff499441fc61e21273f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
